---
antora:
  name: modules
  dir: www
  modules:
    - name: "01-installation"
      label: "Installation"
      solveButton: false
    - name: "02-create-blueprint"
      label: "Create Blueprint"
      solveButton: false
    - name: "03-build-image"
      label: "Build Image"
      solveButton: false
    - name: "04-inspect"
      label: "Inspect"
      solveButton: false
    - name: "05-troubleshooting"
      label: "Troubleshooting"
      solveButton: false

tabs:
  - name: ">_ terminal"
    url: /wetty
