[[create-a-blueprint-from-a-file-1]]
== Create a blueprint from a file

First, look at what blueprints are available on the system.

....
composer-cli blueprints list
....

This system has no existing blueprints. So, let us go ahead and create a
blueprint.

The `+composer-cli+` will take input as a TOML formatted file (Tom’s
Obvious Minimal Language) that describes the blueprint used to define
our machine image.

To save some time look at the *node-app-server.toml* file that has
already been pre-created using a tool like `+cat+` or `+less+`.

....
cat node-app-server.toml
....

The name of the blueprint is called *node-app-server*. It is recommended
that you also include a description so that others using this blueprint
know what system image they are building. At this point, the blueprint
file does not have any packages but we will add the `+nodejs+` and
`+nginx+` packages to it.

`+nodejs+` is distributed as an application stream for Red Hat
Enterprise Linux, so you will need to add a *[[packages]]* section to
the node-app-server.toml file adding `+nodejs+` to the build.

....
printf '\n[[packages]]\nname = "nodejs"\nversion = "*"\n' | sudo tee -a node-app-server.toml
....

The `+printf+` command appends the following formatted stanza to the
node-app-server.toml file.

Similarly, add the `+nginx+` package to the blueprint file.

....
printf '\n[[packages]]\nname = "nginx"\nversion = "*"\n' | sudo tee -a node-app-server.toml
....

In order to create the blueprint from the local TOML file, we will use
the `+blueprints push+` cli option.

....
composer-cli blueprints push node-app-server.toml
....

To verify that your update has been made, review the log of changes made
to the node-app-server blueprint.

....
composer-cli blueprints changes node-app-server
....

____
*Note:* in the above command output, your date and time will be
different than the date and time that appears in the example output.
____

You can also review the contents of the node-app-server blueprint to
verify that the `+nodejs+` and `+nginx+` modules are reflected in the
active version of the blueprint instructions.

....
composer-cli blueprints show node-app-server
....

In the above output, you can see that the `+nodejs+` and `+nginx+`
packages are now included in the node-app-server blueprint definition.
