[[building-a-machine-image-1]]
== Building a machine image

Use the `+composer-cli+` command to start a compose based on the
node-app-server blueprint. For this lab, you will use the output format
of *qcow2*. However, you could build many different types of images
including:

[cols=",^",options="header",]
|===
|Output type |Details
|ami |Amazon EC2
|openstack |OpenStack image
|qcow2 |qcow2 image
|rhel-edge-commit |RHEL edge image
|tar |tar archive
|vhd |virtual hard disk
|vmdk |Virtual Machine disk
|===

....
composer-cli compose start node-app-server qcow2
....

The compose, or build of the image, is tracked using a UUID, in the
above example output, 00403772-ff12-43d4-b09a-bddf28f20709. Your UUID
should be different and unique to your build.

Composes are queued and completed in the order that they were received.
You can look at the status of the queue using
`+composer-cli compose status+`.

....
composer-cli compose status
....

The status will display all queued (WAITING), running (RUNNING), and
completed (FINISHED) composes.

Please click `+Next+` to advance to the next challenge in this lab.
